# Generated by Django 5.0.4 on 2024-06-17 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(default='default_image.jpg', upload_to='novedades/'),
        ),
        migrations.AddField(
            model_name='novedad',
            name='tipo_imagen',
            field=models.CharField(choices=[('atencion', 'Imagen de atención'), ('coopedaro', 'Imagen de Coopedaro'), ('matriculacion', 'Imagen de matriculación'), ('mesas_examen', 'Imagen de mesas de examen')], default='atencion', max_length=20),
        ),
    ]
